commit_message: '[ci skip]'
files:
  - source: /src/main/resources/MacIntegrationsBundle.properties
    translation: /src/main/resources/MacIntegrationsBundle_%two_letters_code%.properties
    escape_quotes: 0
    escape_special_characters: 0
    skip_untranslated_files: true
    skip_untranslated_strings: true