/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_macos_tray_MacTrayMenuController */

#ifndef _Included_org_cryptomator_macos_tray_MacTrayMenuController
#define _Included_org_cryptomator_macos_tray_MacTrayMenuController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_macos_tray_MacTrayMenuController
 * Method:    nativeShowTrayIcon
 * Signature: ([BLjava/lang/String;Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_MacTrayMenuController_nativeShowTrayIcon
  (JNIEnv *, jclass, jbyteArray, jstring, jobject);

/*
 * Class:     org_cryptomator_macos_tray_MacTrayMenuController
 * Method:    nativeUpdateTrayIcon
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_MacTrayMenuController_nativeUpdateTrayIcon
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_cryptomator_macos_tray_MacTrayMenuController
 * Method:    nativeUpdateTrayMenu
 * Signature: (Lorg/cryptomator/macos/tray/MacTrayMenuController/NativeMenu;)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_MacTrayMenuController_nativeUpdateTrayMenu
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_cryptomator_macos_tray_MacTrayMenuController
 * Method:    nativeSetBeforeOpenCallback
 * Signature: (Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_MacTrayMenuController_nativeSetBeforeOpenCallback
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
