/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_macos_autostart_MacLaunchServices_Native */

#ifndef _Included_org_cryptomator_macos_autostart_MacLaunchServices_Native
#define _Included_org_cryptomator_macos_autostart_MacLaunchServices_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_macos_autostart_MacLaunchServices_Native
 * Method:    isLoginItemEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_macos_autostart_MacLaunchServices_00024Native_isLoginItemEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_macos_autostart_MacLaunchServices_Native
 * Method:    enableLoginItem
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_macos_autostart_MacLaunchServices_00024Native_enableLoginItem
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_macos_autostart_MacLaunchServices_Native
 * Method:    disableLoginItem
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_macos_autostart_MacLaunchServices_00024Native_disableLoginItem
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
