/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_macos_tray_DockTileIcon_Native */

#ifndef _Included_org_cryptomator_macos_tray_DockTileIcon_Native
#define _Included_org_cryptomator_macos_tray_DockTileIcon_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_macos_tray_DockTileIcon_Native
 * Method:    applyIcon
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_macos_tray_DockTileIcon_00024Native_applyIcon
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
