/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_macos_uiappearance_MacSystemAppearance_Native */

#ifndef _Included_org_cryptomator_macos_uiappearance_MacSystemAppearance_Native
#define _Included_org_cryptomator_macos_uiappearance_MacSystemAppearance_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_macos_uiappearance_MacSystemAppearance_Native
 * Method:    getCurrentInterfaceStyle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cryptomator_macos_uiappearance_MacSystemAppearance_00024Native_getCurrentInterfaceStyle
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_macos_uiappearance_MacSystemAppearance_Native
 * Method:    registerObserverWithListener
 * Signature: (Lorg/cryptomator/macos/uiappearance/MacSystemAppearanceListener;)J
 */
JNIEXPORT jlong JNICALL Java_org_cryptomator_macos_uiappearance_MacSystemAppearance_00024Native_registerObserverWithListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cryptomator_macos_uiappearance_MacSystemAppearance_Native
 * Method:    deregisterObserver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_uiappearance_MacSystemAppearance_00024Native_deregisterObserver
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
