/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_macos_tray_ActivationPolicy_Native */

#ifndef _Included_org_cryptomator_macos_tray_ActivationPolicy_Native
#define _Included_org_cryptomator_macos_tray_ActivationPolicy_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_macos_tray_ActivationPolicy_Native
 * Method:    transformToAccessory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_ActivationPolicy_00024Native_transformToAccessory
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_macos_tray_ActivationPolicy_Native
 * Method:    transformToRegular
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_ActivationPolicy_00024Native_transformToRegular
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
