/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_macos_tray_MacTrayMenuController_Native */

#ifndef _Included_org_cryptomator_macos_tray_MacTrayMenuController_Native
#define _Included_org_cryptomator_macos_tray_MacTrayMenuController_Native
#ifdef __cplusplus
extern "C" {
#endif
#undef org_cryptomator_macos_tray_MacTrayMenuController_Native_ROOT_MENU
#define org_cryptomator_macos_tray_MacTrayMenuController_Native_ROOT_MENU 0LL
/*
 * Class:     org_cryptomator_macos_tray_MacTrayMenuController_Native
 * Method:    showTrayIcon
 * Signature: ([BLjava/lang/String;Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_MacTrayMenuController_00024Native_showTrayIcon
  (JNIEnv *, jobject, jbyteArray, jstring, jobject);

/*
 * Class:     org_cryptomator_macos_tray_MacTrayMenuController_Native
 * Method:    updateTrayIcon
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_MacTrayMenuController_00024Native_updateTrayIcon
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_cryptomator_macos_tray_MacTrayMenuController_Native
 * Method:    clearMenu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_MacTrayMenuController_00024Native_clearMenu
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_macos_tray_MacTrayMenuController_Native
 * Method:    addActionItem
 * Signature: (JLjava/lang/String;ZLjava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_MacTrayMenuController_00024Native_addActionItem
  (JNIEnv *, jobject, jlong, jstring, jboolean, jobject);

/*
 * Class:     org_cryptomator_macos_tray_MacTrayMenuController_Native
 * Method:    addSeparator
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_MacTrayMenuController_00024Native_addSeparator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cryptomator_macos_tray_MacTrayMenuController_Native
 * Method:    addSubMenuItem
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_cryptomator_macos_tray_MacTrayMenuController_00024Native_addSubMenuItem
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cryptomator_macos_tray_MacTrayMenuController_Native
 * Method:    setBeforeOpenMenuListener
 * Signature: (Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_tray_MacTrayMenuController_00024Native_setBeforeOpenMenuListener
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
