/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_macos_uiappearance_AppAppearance_Native */

#ifndef _Included_org_cryptomator_macos_uiappearance_AppAppearance_Native
#define _Included_org_cryptomator_macos_uiappearance_AppAppearance_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_macos_uiappearance_AppAppearance_Native
 * Method:    setToAqua
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_uiappearance_AppAppearance_00024Native_setToAqua
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_macos_uiappearance_AppAppearance_Native
 * Method:    setToDarkAqua
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_macos_uiappearance_AppAppearance_00024Native_setToDarkAqua
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
