name: Build

on:
  [push]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    env:
      BUILD_VERSION: SNAPSHOT
    outputs:
      artifact-version: ${{ steps.setversion.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: bintray-jcenter
          server-username: BINTRAY_USERNAME
          server-password: BINTRAY_API_KEY
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Ensure to use tagged version
        run: mvn versions:set --file ./pom.xml -DnewVersion=${GITHUB_REF##*/}
        if: startsWith(github.ref, 'refs/tags/')
      - name: Export the project version to the job environment and fix it as an ouput of this job
        id: setversion
        run: |
          v=$(mvn help:evaluate "-Dexpression=project.version" -q -DforceStdout)
          echo "BUILD_VERSION=${v}" >> $GITHUB_ENV
          echo "::set-output name=version::${v}"
        shell: bash
      - name: Build and Test
        run: mvn -B install
      - name: Upload .jars
        uses: actions/upload-artifact@v2
        with:
          name: integrations-mac-${{ env.BUILD_VERSION }}
          path: target/integrations-mac-*.jar
      - name: Build and deploy to jcenter
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn -B deploy -DskipTests
        env:
          BINTRAY_USERNAME: cryptobot
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
